[package]
name = "exercise-a"
version = "0.1.0"
authors = ["A Ruiz <luis.alonso.16@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
